/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio1.vista;

import Ejercicio1.controlador.Vehiculos.MarcaController; 
import Ejercicio1.vista.ModeloTabla.TablaMarca;
import javax.swing.JOptionPane;
/**
 *
 * @author diego
 */
public class Frm_Marcas extends javax.swing.JFrame {
    
    private MarcaController mc = new MarcaController();
    private TablaMarca tablaMarca = new TablaMarca();
    private Integer fila = -1;

    /**
     * Creates new form Frm_Marcas
     */
    public Frm_Marcas() {
        initComponents();
        limpiar();
    }
    
    public void limpiar() {
        txt_regMarca.setText("");
        txt_color.setText("");
        cbx_precios.setSelectedIndex(0);
        cargarTabla();
        mc.setMarca(null);
    }
    
    public void cargarTabla() {
        tablaMarca.setLista(mc.listado());
        tbl_marca.setModel(tablaMarca);

        tbl_marca.updateUI();
    }
    
    public void guardar() {
        if (txt_color.getText().trim().isEmpty() || txt_regMarca.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene los campos vacíos", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            mc.getMarca().setNombre(txt_regMarca.getText().trim());
            mc.getMarca().setColorMarca( txt_color.getText().trim());
            mc.getMarca().setTipoPrecio(cbx_precios.getSelectedItem().toString().trim());
            if (mc.guardar()) {
                JOptionPane.showMessageDialog(null, "Marca Registrada", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo guardar", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_regMarca = new javax.swing.JTextField();
        txt_color = new javax.swing.JTextField();
        cbx_precios = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_marca = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("REGISTRO DE MARCAS"));
        jPanel1.setLayout(null);

        jLabel1.setText("Nombre de Marca:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 30, 120, 18);

        jLabel3.setText("Color Distintivo:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 70, 102, 18);

        jLabel2.setText("Rango de Precios:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 110, 140, 18);
        jPanel1.add(txt_regMarca);
        txt_regMarca.setBounds(190, 30, 190, 24);
        jPanel1.add(txt_color);
        txt_color.setBounds(190, 70, 190, 24);

        cbx_precios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Económicos", "Normal", "Lujo" }));
        jPanel1.add(cbx_precios);
        cbx_precios.setBounds(190, 110, 190, 24);

        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(80, 150, 120, 24);

        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(220, 150, 120, 24);

        tbl_marca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_marca);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 200, 360, 130);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 430, 380);

        setSize(new java.awt.Dimension(462, 428));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        guardar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Frm_Auto auto = new Frm_Auto();
        this.setVisible(false);
        auto.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Marcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Marcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Marcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Marcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Marcas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbx_precios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_marca;
    private javax.swing.JTextField txt_color;
    private javax.swing.JTextField txt_regMarca;
    // End of variables declaration//GEN-END:variables
}
